# Generated by Django 4.1 on 2026-04-03 00:56

from django.db import (migrations, models)

import cinema.models


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie',
            field=models.ImageField(null=True, upload_to=cinema.models.create_custom_path),
        ),
    ]

